export const getData = async ()=>{
   try{
      
   }catch(erro){
      console.log("Error");
   }
}